docs: add PITR runbook documentation
bcgov/cas-postgres pull request #126
Opened 2022-06-17 18:08 UTC by dleard

2022-06-17 22:17 UTC, matthieu-foucault requested changes
Some example `oc` commands and/or screenshots of the OpenShift console would be valuable here. Remember that when this is needed, people will be in a stressful situation, so you want to do as much hand holding as possible in the runbook.

2022-06-17 22:17 UTC, matthieu-foucault commented on README.md
> +In the event a database needs to be recovered from a backup to a specific point in time, these are the steps to follow. Patroni is shipped with a [clone_with_wale](https://app.zenhub.com/workspaces/c
```suggestion
In the event a database needs to be recovered from a backup to a specific point in time, these are the steps to follow. Spilo is shipped with a [clone_with_wale](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/751) method that we can leverage to handle this for us with the addition of a few environment variables.
```

2022-06-17 22:17 UTC, matthieu-foucault commented on README.md
> +In the event a database needs to be recovered from a backup to a specific point in time, these are the steps to follow. Patroni is shipped with a [clone_with_wale](https://app.zenhub.com/workspaces/c
the link for `clone_with_wale` is wrong

2022-06-17 22:17 UTC, matthieu-foucault commented on README.md
> +- Scale the patroni statefulset down to 0
you want to scale down before changing the env variables

2022-06-17 22:17 UTC, matthieu-foucault commented on README.md
> +
Showing an example of the expected patroni logs here would be useful

2022-11-07 17:56 UTC, pbastia approved these changes
awesome

2022-11-07 20:03 UTC, merged